spring.datasource.url=jdbc:postgresql://dpg-d8oticsvikkc7391ehlg-a.oregon-postgres.render.com:5432/gestion_turnos_md8a
spring.datasource.username=gestion_turnos_md8a_user
spring.datasource.password=3RutP6JaYlrHjS5cQO6lVHbrFYEGaRBB
