
spring.datasource.url=${SPRING_DATASOURCE_URL:https://gestiondeturnos-dnme.onrender.com}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gestion_turnos_md8a_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:3RutP6JaYlrHjS5cQO6lVHbrFYEGaRBB}
