version: '3.8'

services:
  db:
    image: postgres:15

    container_name: gestion-turnos_db
    restart: always
    environment:
      POSTGRES_USER: admin_gestion
      POSTGRES_PASSWORD: gestion_pass_2026
      POSTGRES_DB: gestion_turnos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: